[WIP] Upgrade to WasmEdge 0.9.0-rc.1
second-state/wasmedge-extensions pull request #5
Opened 2021-11-10 08:55 UTC by dm4

2021-11-10 13:53 UTC, hydai requested changes

2021-11-10 13:53 UTC, hydai commented on .github/actions/build-from-source/action.yml
> +name: Build wasmedge-core
`wasmedge-extension` ?

2021-11-10 13:55 UTC, dm4 commented on .github/actions/build-from-source/action.yml
> +name: Build wasmedge-core
fixed.

2021-11-11 03:53 UTC, hydai approved these changes

2021-11-11 03:53 UTC, merged